name: Catalog Service CI

on:
  push:
    branches:
       - '**'
    paths:
      - 'src/Services/CatalogService/**'
      - '.github/workflows/catalog-ci.yml'
  pull_request:
    branches: [ "develop", "main" ]
    paths:
      - 'src/Services/CatalogService/**'
      - '.github/workflows/catalog-ci.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore src/Services/CatalogService/FoodGo.CatalogService.Api/FoodGo.CatalogService.Api.csproj

      - name: Build
        run: dotnet build src/Services/CatalogService/FoodGo.CatalogService.Api/FoodGo.CatalogService.Api.csproj --configuration Release --no-restore

      - name: Run Domain Tests
        run: dotnet test tests/FoodGo.CatalogService.Domain.Tests/FoodGo.CatalogService.Domain.Tests.csproj --configuration Release --verbosity normal

      - name: Run Application Tests
        run: dotnet test tests/FoodGo.CatalogService.Application.Tests/FoodGo.CatalogService.Application.Tests.csproj --configuration Release --verbosity normal